version: '3'
services:
  website:
    image: php:apache
    environment:
      USERNAME: "toto"
      PASSWORD: "tata"
    volumes:
      - ./website:/var/www/html
    depends_on:
      - api
    ports:
      - 8002:80
  api:
    image: pozos_image
    volumes:
      - ./home/centos/dockerTp1/student-list/simple_api/student_age.json:/data/student.json
    ports:
      - 4000:5000

